site_name: Rocket MV BASIC
nav:
    - Home: 'index.md'
    - Usage:
        - 'Accounts Settings': 'usage/Accounts.md'
        - 'Catalog Settings': 'usage/Catalog.md'
        - 'Compile': 'usage/Compile.md'
        - 'Configuration': 'usage/Configuration.md'
        - 'Code Lens': 'usage/CodeLens.md'
        - 'Compatibility': 'usage/Compatibility.md'
        - 'Customized Documentation': 'usage/CustomizeDoc.md'
        - 'DAP Binaries': 'usage/DAPRelease.md'
        - 'Debugging': 'usage/Debugging.md'
        - 'Document Symbol': 'usage/DocumentSymbol.md'
        - 'Diagnostics': usage/Diagnostics.md
        - 'Hash File Edit Locking': 'usage/HashedFileEditing.md'
        - 'File Locking': 'usage/FileLock.md'
        - 'Folding': 'usage/Folding.md'
        - 'Formatting': 'usage/Formatting.md'
        - 'GaraSign': 'usage/GaraSign.md'
        - 'Group View': 'usage/GroupView.md'
        - 'Hover': 'usage/Hover.md'
        - 'INCLUDE settings': 'usage/Include.md'
        - 'Logging': 'usage/Logging.md'
        - 'Multiple Workspace Folders': 'usage/MultipleWorkspaceFolders.md'
        - 'Online Editing': 'usage/OnlineEditing.md'
        - 'References': 'usage/References.md'
        - 'Semantic Highlighting': 'usage/SemanticHighlighting.md'
        - 'Signature Help': 'usage/SignatureHelp.md'
        - 'Using Auto Completion': 'usage/Completion.md'
        - 'Using Definition': 'usage/Definition.md'
        - 'Using Rename': 'usage/Rename.md'
        - 'U2 Connection Settings': 'usage/Connection.md'
    - FAQ: 'usage/FAQ.md'
    - Change Log:
        - 'Change Log': 'usage/CHANGELOG.md'
        - 'Known Issues': 'usage/KnownIssues.md'
        